contact/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('',views.contact, name="contact")
]

home/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from .views import home

urlpatterns = [
    path('', home , name= 'home')
]

jadwal/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from . import views

app_name ='jadwal'

urlpatterns = [
    path('',views.schedule, name="schedule"),
    path('create_schedule/',views.create_schedule, name="create_schedule"),
    path('<str:id>/',views.lihat_jadwal, name="lihat_jadwal"),
    path('<str:id>/delete_item/',views.delete_item, name="delete_item")
]

story4ppw/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('contact/', include('contact.urls')),
    path('schedule/', include('jadwal.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/',include('story9.urls'))
]

story7/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from . import views

app_name ='experience'

urlpatterns = [
    path('',views.pengalaman, name="pengalaman"),
]

story8/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from . import views

app_name ='search'

urlpatterns = [
    path('',views.search, name="cari"),
    path('data/', views.data, name='books')
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
]

contact/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

jadwal/models.py
from django.db import models


SEMESTER = ( 
    ("1", "Gasal 2019/2020"), 
    ("2", "Genap 2019/2020"), 
    ("3", "Gasal 2020/2021"), 
    ("4", "Genap 2020/2021"), 
    ("5", "Gasal 2021/2022"), 
    ("6", "Genap 2021/2022"), 
    ("7", "Gasal 2022/2023"), 
    ("8", "Genap 2022/2023"), 
) 
class Jadwal (models.Model):
    nama_matkul = models.CharField(max_length =20, null=True)
    pengajar = models.CharField(max_length =20)
    jumlah_sks = models.CharField(max_length = 10)
    deskripsi = models.CharField(max_length =60)
    semester = models.CharField(max_length =20, choices = SEMESTER, default="3" )
    ruang = models.CharField(max_length=10, null=True)

    def __str__(self):
        return "{}".format(self.nama_matkul)

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

jadwal/forms.py
from django import forms
from . import models

class Input_Form(forms.ModelForm):
    class Meta:
        model = models.Jadwal
        fields = "__all__"
        
    nama_matkul = forms.CharField(
        widget= forms.TextInput(
            attrs= {
                "class" : "editform",
                "max_length" : 50,
                "required"  : True,
                "placeholder"   : "Subjects"
            }
        )
    )

    pengajar = forms.CharField(
        widget = forms.TextInput(
            attrs = {
                 "class" : "editform",
                "required"  : True,
                "placeholder" : "Lecturer",
            }
        )
    )

    jumlah_sks = forms.CharField(
        widget= forms.TextInput(
            attrs = {
                "class" : "editform",
                "required" : True,
                "placeholder" : "SKS"
            }
        )
    )

    deskripsi= forms.CharField(
        widget = forms.TextInput(
            attrs = {
                "class" : "editform editdescription",
                "placeholder" : "Description",
                "required"  : True,
            }
        )
    )

    

    ruang= forms.CharField(
        widget = forms.TextInput(
            attrs = {
                "class" : "editform",
                "placeholder" : "Classroom",
                "required"  : True,
            }
        )
    )

    

story9/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=30, required=False, help_text='Optional.')
    full_name = forms.CharField(max_length=30, required=False, help_text='Optional.')

    class Meta:
        model = User
        fields = ('username', 'full_name','email', 'password1', 'password2')

contact/views.py
from django.shortcuts import render
from django.http import HttpResponse

def contact(request):
    return render(request,'contact.html')

home/views.py
from django.http import HttpResponse
from django.shortcuts import render

def home(request):
    return render(request,'home.html')

jadwal/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from .models import Jadwal
from . import forms


def schedule(request):
    jadwal = Jadwal.objects.all()
    response = {
        'jadwal' :jadwal,
    }

    return render(request,'schedule.html', response)

def create_schedule(request):
    form = forms.Input_Form()
    if (request.method == "POST"):
        form = forms.Input_Form(request.POST)
        if form.is_valid():
            form.save()
            return redirect('jadwal:schedule')
        else:
        # Added else statment
            msg = 'Errors: %s' % form.errors.as_text()
            return HttpResponse(msg, status=400)
    return render(request,'create_schedule.html', {'form':form} )

def lihat_jadwal(request,id):
    objek = Jadwal.objects.get(id=id)
    response = {
        'objek' : objek,
    }
    return render (request, 'detail.html', response)

def delete_item(request,id):
    Jadwal.objects.get(id = id).delete()
    return redirect('jadwal:schedule')

story7/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect


def pengalaman(request):
    return render(request,'experience.html')

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import json
import requests

# Create your views here.
def search(request):
    return render(request, 'search.html')

def data(request):
    try:
        q = request.GET['q']
    except:
        q = "quilting"
    
    json_read = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + q).json()

    return JsonResponse(json_read)

story9/views.py
from django.shortcuts import render, redirect
from .forms import *
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout


# Create your views here.
def index(request):
    return render(request, 'story9.html')

def login(request):
    if request.method == 'POST': 
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request, user)
            
            return redirect('/story9/')
        else:
            messages.error(request, 'Username or password is incorrect')
    return render(request, 'login.html')

def logout(request):
    auth_logout(request)
  
    return redirect('/story9/')

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            auth_login(request, user)
            messages.success(request, "Successfully created a user with username {}".format(username))
            return redirect('/story9/')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form' : form})

contact/templates/contact.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<section class= "section1 section5" id="contact">
    <div class="contact">
      <strong style="font-size: 45px; padding: 70px; padding-bottom: 20px; font-weight: bolder;">Contact</strong>
      <p style="font-size: 30px;">Need something? Let's be connected.</p>
      <a href="mailto:fadhilahumairah24@gmail.com">
        <button type="button" class="btn btn-light button">hit me up</button>
      </a>
    </div>

    <div class="contact contact2">
      <p style="margin-bottom: 5px;">Feel free to have a chit-chat with me</p>
      <div class = "sosmed">
        <a href="https://www.instagram.com/fadhilahumairah/"><img width="30" height="30"  alt="" src="../static/ig.svg"></a>
        <a href=" http://line.me/ti/p/~falaahumairah"><img width="30" height="30" alt="" src="../static/line.svg"></a>
        <a href = "https://twitter.com/Falaahumairah"><img  width="30" height="30" alt="" src="../static/tw.svg"></a>
        <a href = "https://wa.me/082276919191" ><img  width="30" height="30" alt="" src="../static/wa.svg"></a>
        <a href="https://www.linkedin.com/in/fadhilahumairah"><img width="30" height="30" alt="" src="../static/linkedin.svg"></a>
     </div>
    </div>
</section>

{% endblock %}

home/templates/home.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
  <section class="section1" id="home">
    <div class="pertama">
        <div> <p style="font-size: 45px; font-weight: bold;">Hello!</p></div>
        <div style="font-size: 45px;"><h3 style="font-weight: bold;">I'm <strong style="font-weight: bolder;">Fadhila Humairah</strong></h3></div>
        <div><p class="text">So, are you ready to get to know me?</p></div>
        <div><a href="#about"><button type="button" class="btn btn-outline-info" style="font-weight: bold;">more than ready</button></a></div>
      </div>
  </section>


  <section class="section1 section2"  id="about">
    <div class="kedua">
      <div>
        <img class="cakep" src="../static/cakep.jpg" alt="" >
      </div>
      <div class = "konten">
        <strong class="hello">Hello again!</strong>
        <p>
          As it’s said above, my name is Fadhila Humairah (NPM : 1906353990), 
          but call me fala and it’s enough. I’m currently studying at Universitas Indonesia, 
          majoring in Information System (Maung 2019). 
        </p>
        <p>
          I love to learn something new, so that makes me a hardworker. 
          I am also a communicative person, so don’t hesitate to talk to me.
          I don’t have any specific hobby, but i love watching a lot of movies, 
          listening to music, and exploring new things on the internet in my leisure.
        </p>
        <p style="font-weight: bolder;">
          Skills:
        </p>
        <div class="skills">
          <img src="../static/python.svg"  class="skillsicon" alt="">
          <img src="../static/java.svg" class="skillsicon" alt="">
        </div>
      </div>
    </div>
  </section>



  <section class="section3" id="education">
    <div class="ketiga">
      <strong class="education">Educational Background</strong>
      <ul class="listedu" style="list-style-type: none;">
        <li>
           <img src="../static/sd.svg" class="riwayat">
        </li>
        <li >
            <img src="../static/smp.svg" class="riwayat">
        </li>
        <li>
            <img src="../static/sma.svg" class="riwayat">
        </li>
        <li >
            <img src="../static/ui.svg" class="riwayat">
        </li>
      </ul>
    </div>
  </section>


  <section class="section1 section4" id="experience">
    <div class="keempat">
      <strong class="experience">Experience</strong>
      <div class="kotak">
        <img class="prestasi"  src="../static/committe.svg" alt="">
        <img class="prestasi"  src="../static/achievements.svg" alt="" >
      </div>
    </div>
  </section>

{% endblock %}

jadwal/templates/create_schedule.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<section class= "section1 section5" id="contact">
    <div class="contact" >
      <strong style="font-size: 35px; padding: 25px; padding-bottom: 5px; font-weight: bolder;">Add Schedule</strong>
      <p style="font-size: 20px;">By failing to prepare, you are preparing to fail</p>
      <form method="POST" action="{% url 'jadwal:create_schedule' %}"> 
        {% csrf_token %}
        <span >Subjects : </span>
        <br>
        {{ form.nama_matkul }} <br>
        <span >Lecturer : </span>
        <br>
        {{ form.pengajar }} <br>
        <span >SKS : </span>
        <br>
        {{ form.jumlah_sks }} <br>
        <span >Description : </span>
        <br>
        {{ form.deskripsi }} <br>
        <span >Term : </span>
        <br>
        {{ form.semester }} <br>
        <p style="margin-bottom: 0; margin-top: 8px; ">Classroom : </p>
        {{ form.ruang }}
        <br>

        <input class= "btn btn-light button" style="margin-top: 4px;font-size: 15px;"type="submit" value="submit">     
      </form>







    
</section>

{% endblock %}

jadwal/templates/detail.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<section class= "section1 section5" id="contact">
    <div class="contact">
      <strong style="text-decoration: underline; font-size: 40px;  padding: 25px; padding-top : 15vh; font-weight: bolder;color:#5E6472;">{{ objek.nama_matkul }} Details</strong>
        <div class= "details" style="color:#5E6472;">
            <span>Lecturer: {{objek.pengajar}} </span><br>
            <span>SKS     : {{objek.jumlah_sks}}</span><br>
            <span>Description     : {{objek.deskripsi}}</span><br>
            <span>Term    : {{objek.get_semester_display}}</span><br>
            <span>Classroom    : {{objek.ruang}}</span>
        </div>

       
      <a href="delete_item/" >
        <button style="margin-top: 10vh;" type="button" class="btn btn-light button butsub">Remove</button>
      </a>

    </div>

    
</section>

{% endblock %}

jadwal/templates/schedule.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<section class= "section1 section5" id="contact">
    <div class="contact">
      <strong style="font-size: 45px; padding: 25px; padding-bottom: 0px; font-weight: bolder;">Schedule</strong>
      <p style="font-size: 25px; padding-bottom: 5px;">I'm prepared</p>
      <a href="create_schedule/">
        <button style="font-size: 17px; margin-bottom:14px;" type="button" class="btn btn-light button">Add schedule</button>
      </a>

      <p style="text-decoration: underline; font-size: 20px; padding-top: 25px;margin-bottom:5px;font-weight: bolder;">List of Subjects</p>
      {% if jadwal %}
        {% for objek in jadwal %}
  
        <a href={{objek.id}}/ >
          <button style="font-size: 13px; margin:4px; width: 15vh;" class="btn btn-light button"> {{ objek.nama_matkul }}</button>
        </a>
        {% endfor %}
      {% endif %}
   


    </div>

    
</section>

{% endblock %}

story7/templates/experience.html
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'style.css' %}" />


 <script>
     $( function() {
  $( "#accordion" ).accordion({
    header: "> div > h3",
    collapsible: true,

    heightStyle: "content",
    icons:false,
    active: 0

  });
} );


$( document ).ready(function() {
  setButtons();
  $(document).on('click', '.down', function(e) {
  var cCard = $(this).closest('.group');
  var tCard = cCard.next('.group');
  cCard.insertAfter(tCard);
  setButtons();
  });
  
  $(document).on('click', '.up', function(e) {
  var cCard = $(this).closest('.group');
  var tCard = cCard.prev('.group');
  cCard.insertBefore(tCard);
  setButtons();
  });
  
  function setButtons(){
      $('button').show();
      $('.group:first-child  button.up').hide();
      $('.group:last-child  button.down').hide();
  }
  
  });

 </script>
</head>


<style>
    .acc{
        text-align: left;
        padding-left: 20vh; 
        padding-right: 20vh
    }

    button{
        margin-right: 0px;
        justify-content: space-around;
    }

    @media (max-width: 786px){
        .section1{
            height: 150vh;
        }
    }
    
</style>

<body>
<div class="section1 section5" >
    <div class="contact">
      <strong style="font-size: 45px; padding: 25px; padding-bottom: 0px; font-weight: bolder;">Story 7</strong>
      <p style="font-size: 25px; padding-bottom: 5px;"> Welcome </p>

      <div id="accordion" class="acc" style=" font-family: 'Montserrat', sans-serif;">
        <div class="group" >
        <h3  >About Me
            
                <button class="up"><img src="../static/up.png" ></button>
                <button class="down"><img src="../static/down.png" ></button>

        </h3>
        <div>
          <p>Hello, my name is fadhila humairah, but fala is enough. I'm currently studying at University of Indonesia, majoring in Information systems.</p>
        </div>
        </div>

        <div class="group" >
        <h3  >Current activities
            <button class="up" ><img src="../static/up.png" ></button>
                <button  class="down" ><img src="../static/down.png" ></button>

        </h3>
        <div>
          <p>Not a lot, just keep studying so i can pass all of my subjects and becoming a comittee in some of events</p>
        </div>
        </div>
    
        <div class="group" >
        <h3  >Experience
            <button  class="up"><img src="../static/up.png" ></button>
                <button  class="down"><img src="../static/down.png" ></button>

        </h3>
        <div>
          <p>Not so impressive but here we go.</p>
          <ul>
            
            <li>Vice Person in Charge of Roadhshow UIGTM <br>2020-2021</li>
            <li>Staff of Decoration PERAK Fasilkom <br>2020</li>
            <li>HRD of CTF COMPFEST 12 <br>2020</li>
            <li>Staff of Event PMB Fasilkom 2021 <br>2020</li>
            <li>Staff of Roadshow UIGTM <br>2019-2020</li>
          </ul>
        </div>
        </div>

        <div class="group" >
        <h3>Achievements
            <button  class="up" ><img src="../static/up.png" ></button>
            <button  class="down"><img src="../static/down.png" ></button>

        </h3>
        <div>
            <p>Not so impressive but here we go.</p>
            <ul>
              
              <li style="padding-bottom: 5px;">1st Runner Up Debate Competition <br>National English Competition (NEC), 2017</li>
              <li style="padding-bottom: 5px;">Juara 3 Debate Competition (Novice)<br>LIBASH, 2016</li>
              <li style="padding-bottom: 5px;">Juara 2 Lomba Susun Kata Bahasa Jerman<br>Oktoberfest, 2016</li>
            </ul>
          </div>
        </ul>
        </div>
        </div>

      </div>


    </div>


</div>
</body>

   

story8/templates/search.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<style>
    body{
        background-color:  #AED9E0;
    }
</style>
<section class="half container-fluid flex-column flex-lg-row m-auto w-50" id="bg-up" style="color:  #00AFB9;">
    <div class='container'>
        <h3 style ="margin-top: 1vh;">Cari Buku</h3>
        <div class="input">
            <input type="text" id="input" placeholder="cari">
        </div>
        <br>
        <div class="content">
            <table class= "table table-borderless" >
                <thead>
                    <tr style="color: white;">
                        <th scope="col" class="align-middle" style="background-color : #5E6472;">no</th>
                        <th scope="col" class="align-middle" style="background-color : #5E6472;">cover</th>
                        <th scope="col" class="align-middle" style="background-color : #5E6472;">title</th>
                        <th scope="col" class="align-middle" style="background-color : #5E6472;">authors</th>
                        <th scope="col" class="align-middle" style="background-color : #5E6472;">publisher</th>
                        <th scope="col" class="align-middle" style="background-color : #5E6472;">published date</th>
                    </tr>
                </thead>
                <tbody id="konten"></tbody>
            </table>
        </div>
    </div>
    
</section>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
    </script>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
    </script>

<script type="text/javascript" src="{% static 'search.js' %}"></script>





{% endblock %}

story9/templates/login.html
<!DOCTYPE html>
{% load static %}
{% include "base.html" %} 

<style>
    body{
        text-align: center;
        justify-content: center;
        color:  #00AFB9;
    }
</style>
<section class="section1">
    <h1 class="title" style="padding-top: 20vh; font-weight: bolder;">login</h1>
    <form  action="" method="POST" style="font-weight: bold;">
    {% csrf_token %}
    <p  style="margin-bottom: 5px;">username: </p><input style="margin-bottom: 10px;" type="text" name="username">
    <p  style="margin-bottom: 5px;">password: </p><input type="password" name="password"> <br> <br>
    <button style = "border: 0px; font-size: 20px; padding: 20px; padding-top: 0px; padding-bottom: 0px;"class=" button" type="submit">login</button>

    
    {%for message in messages%}
    <div class="alert alert-danger" style="margin: 80vh; margin-top: 10px; margin-bottom: 0px;">
       {{message}}
    </div>
    {%endfor%}
   
</form>
</section>


</body>
</html>

story9/templates/signup.html
{% load static %}
{% include "base.html" %} 

<style>
    body{
        background-color: #AED9E0;
       
        text-align: left;
        color:  #00AFB9;
    }
</style>


<h1 style="padding-left: 10vh;" class="title">sign up</h1>
<form style="padding-left: 10vh;" action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button  class="button" type="submit" style="border: 0px;">Submit</button>
</form>

story9/templates/story9.html
{% load static %}
{% include "base.html" %} 
<style>
    body{
        text-align: center;
        justify-content: center;
        color:  #00AFB9;
    }
</style>
        
    <body>
    <section class="section1">
        <br>
        <br>
        <br>
        <div class="container"> 
        <h1 style="font-weight: bolder;"id= "login">
            {% if user.is_authenticated %}
            hello, {{ user }} <br> </h1>
        <div style="font-weight: bold; font-size: 20px;">
            hope you have a nice day
        </div>
        <div  class=" button" style="padding-top: 50px;" id= "logout">
            <a href= "logout/" style="color: #5E6472;">logout</a>
        </div>
          {% else %}
          <h3 style="text-align: center; padding-bottom: 5vh; font-weight: bolder ; color:  #5E6472;">Login for the best experience</h3>
            <a class="button" href= "login/" >login</a>
         
        </div>
        <div id= "signup">
            <a class="button"href= "signup/" >sign up</a>
            {% endif %}
        </div>
        </div>
    </section>
        
    </body>